CREATE DATABASE IF NOT EXISTS Movies_DB;
USE Movies_DB;

CREATE TABLE Director (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(200) NOT NULL,
    Nationality VARCHAR(100) NOT NULL,
    Age INT NOT NULL,
    Active BOOLEAN NOT NULL DEFAULT 1   
);

CREATE TABLE Movies (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    ReleaseYear DATE NOT NULL,
    Gender VARCHAR(50) NOT NULL,
    Duration TIME NOT NULL,
    FKDirector INT NOT NULL,
    FOREIGN KEY (FKDirector) REFERENCES Director(id)
);